apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: vhalme/auth-server:x86_0.0.9
        ports:
        - containerPort: 3001
        env:
        - name: AUTH_DB_HOST
          value: postgres
        - name: AUTH_DB_USER
          value: "$AUTH_DB_USER"
        - name: AUTH_DB_PASSWORD
          value: "$AUTH_DB_PASSWORD"
        - name: AUTH_HTTP_PORT
          value: "$AUTH_HTTP_PORT"
        - name: AUTH_FB_APPID
          value: "$AUTH_FB_APPID"
        - name: AUTH_FB_SECRET
          value: "$AUTH_FB_SECRET"
        - name: GOOGLE_OAUTH_ID
          value: "$GOOGLE_OAUTH_ID"
        - name: GOOGLE_OAUTH_SECRET
          value: "$GOOGLE_OAUTH_SECRET"
        - name: PG_SSL_CERT_DIR
          value: "/app/pg/ssl/certs"
        - name: APP_URL
          value: https://solarwindmetaverse.com