apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  type: NodePort
  ports:
  - name: auth-server
    port: 3001
    targetPort: 3001
  selector:
    app: auth-server